### ISSUE TITLE
GitHub action does not find database table

### ISSUE THREAD

**Issue by pemistahl** [rusqlite/rusqlite#878]
Hi, I'm not sure where to ask for help about this. It may not be a rusqlite problem, maybe an SQLite or even Linux one. Or it's just related to GitHub Actions. I don't really know. But here we go:

I have written a command-line tool that unzips and accesses a bundled SQLite database which was created with rusqlite. On my local machine, everything works fine. However, [in the GitHub Actions pipeline](https://github.com/pemistahl/chr/runs/1646184911?check_suite_focus=true#step:10:106), one of the integration tests which access the database always fails on the latest Ubuntu. It's not always the same test, sometimes they take turns. 

In the same GitHub action step, the bundled database is unzipped in memory, written do disk and then accessed by the integration test. Could it be that two separate threads are trying to access the database at the same time while the access is not thread-safe? 

This is the stacktrace (the bottom is probably more interesting than the top):

```
command=`"/home/runner/work/chr/chr/target/x86_64-unknown-linux-musl/debug/chr" "--no-paging" "\xc3\x84" "@" "$" "\xc3\x9f" "!"`
code=101
stdout=Preparing Unicode character database, please wait a moment...
Database is ready

stderr=thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: UnicodeData"))', src/main.rs:175:48
stack backtrace:

0: 0x77ce50 - std::backtrace_rs::backtrace::libunwind::trace::hbf39669e8eecfe2e
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96

1: 0x77ce50 - std::backtrace_rs::backtrace::trace_unsynchronized::h6536955678967bbe
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66

2: 0x77ce50 - std::sys_common::backtrace::_print_fmt::h0a8adae8fc4ef9e6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79

3: 0x77ce50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcce50b82ca571d0c
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58

4: 0x7b3a6c - core::fmt::write::h7410fe2c9751fa7d
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080

5: 0x7793b2 - std::io::Write::write_fmt::h4c0dae1f7b98e3de
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516

6: 0x77f06d - std::sys_common::backtrace::_print::hbe0941286da8faf6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61

7: 0x77f06d - std::sys_common::backtrace::print::haeefde137ed8b41c
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48

8: 0x77f06d - std::panicking::default_hook::{{closure}}::hc7652abb91610a87
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208

9: 0x77ed18 - std::panicking::default_hook::hbbf715ca996ff6f0
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227

10: 0x77f751 - std::panicking::rust_panic_with_hook::ha99d6ba4510ede21
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577

11: 0x77f2f9 - std::panicking::begin_panic_handler::{{closure}}::ha0a3abfa52be3c7e
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484

12: 0x77d2dc - std::sys_common::backtrace::__rust_end_short_backtrace::h928c9a243067ad58
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153

13: 0x77f2b9 - rust_begin_unwind
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483

14: 0x7b2d81 - core::panicking::panic_fmt::h8da5cc7278cbda07
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85

15: 0x7b2ba3 - core::option::expect_none_failed::hf9a8bfb1faa70e27
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234

16: 0x402349 - core::result::Result<T,E>::unwrap::h7deec3210076545b
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973

17: 0x406ee8 - chr::retrieve_results::h443b311e393e8b95
at /home/runner/work/chr/chr/src/main.rs:175

18: 0x41c36a - chr::search_database::h7155194fb2b2f02c
at /home/runner/work/chr/chr/src/main.rs:163

19: 0x41b6ac - chr::main::h36b386a029e7d44e
at /home/runner/work/chr/chr/src/main.rs:98

20: 0x41845b - core::ops::function::FnOnce::call_once::hc0b2e9cc194095c0
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227

21: 0x40787e - std::sys_common::backtrace::__rust_begin_short_backtrace::h5a8f00dd7040fab4
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137

22: 0x407851 - std::rt::lang_start::{{closure}}::h163fbbb0aba62381
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:66

23: 0x77fad9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd103a7da4f5f3e68
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259

24: 0x77fad9 - std::panicking::try::do_call::h57ffdb711764a297
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381

25: 0x77fad9 - std::panicking::try::h3e0e9184725a0283
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345

26: 0x77fad9 - std::panic::catch_unwind::hfc94089ba6b2ab6d
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382

27: 0x77fad9 - std::rt::lang_start_internal::h0d4e7f90d4e375f7
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51

28: 0x407827 - std::rt::lang_start::h1cd54642b1db321b
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:65

29: 0x41ea4a - main

', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:158:13
stack backtrace:
0: 0x4803d0 - std::backtrace_rs::backtrace::libunwind::trace::hbf39669e8eecfe2e
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96

1: 0x4803d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6536955678967bbe
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66

2: 0x4803d0 - std::sys_common::backtrace::_print_fmt::h0a8adae8fc4ef9e6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79

3: 0x4803d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcce50b82ca571d0c
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58

4: 0x4b856c - core::fmt::write::h7410fe2c9751fa7d
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080

5: 0x408c16 - std::io::Write::write_fmt::h4b74cd0e6d4677ae
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516

6: 0x47a3cd - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h62df4730827dad76
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/impls.rs:179

7: 0x4828ed - std::sys_common::backtrace::_print::hbe0941286da8faf6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61

8: 0x4828ed - std::sys_common::backtrace::print::haeefde137ed8b41c
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48

9: 0x4828ed - std::panicking::default_hook::{{closure}}::hc7652abb91610a87
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208

10: 0x482542 - std::panicking::default_hook::hbbf715ca996ff6f0
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:224

11: 0x482fd1 - std::panicking::rust_panic_with_hook::ha99d6ba4510ede21
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577

12: 0x482b79 - std::panicking::begin_panic_handler::{{closure}}::ha0a3abfa52be3c7e
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484

13: 0x48085c - std::sys_common::backtrace::__rust_end_short_backtrace::h928c9a243067ad58
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153

14: 0x482b39 - rust_begin_unwind
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483

15: 0x482aeb - std::panicking::begin_panic_fmt::haf20a47748297afe
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437

16: 0x444101 - assert_cmd::assert::Assert::success::hf1892b8c39f248b6
at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:158

17: 0x400322 - cli_integration_tests::succeeds_with_character_search_option::h633f2542490b5217
at /home/runner/work/chr/chr/tests/cli_integration_tests.rs:26

18: 0x40465a - cli_integration_tests::succeeds_with_character_search_option::{{closure}}::h25ad6156d25b080e
at /home/runner/work/chr/chr/tests/cli_integration_tests.rs:23

19: 0x4053fe - core::ops::function::FnOnce::call_once::h7efdcbfceb83d8eb
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227

20: 0x42fa93 - core::ops::function::FnOnce::call_once::h3dd146acb242d097
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227

21: 0x42fa93 - test::__rust_begin_short_backtrace::h4c0d2970ff877aed
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:516

22: 0x42df88 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he7f1b58b7fbfd1db
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042

23: 0x42df88 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h51eb65f8ae7d43b1
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:308

24: 0x42df88 - std::panicking::try::do_call::hf7c85dd7d38e9c15
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381

25: 0x42df88 - std::panicking::try::hd91171643a91eb6b
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345

26: 0x42df88 - std::panic::catch_unwind::h4a189bce13b36bfc
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382

27: 0x42df88 - test::run_test_in_process::h850ea7006e95a086
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:543

28: 0x42df88 - test::run_test::run_test_inner::{{closure}}::h3dcf7fd11719467b
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:449

29: 0x407f96 - std::sys_common::backtrace::__rust_begin_short_backtrace::he0745ea92d7c373a
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137

30: 0x40d0a5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd099acd06f3aa18a
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/thread/mod.rs:464

31: 0x40d0a5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb9d08264c93d16c6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:308

32: 0x40d0a5 - std::panicking::try::do_call::h707e5d7c0b6143b8
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381

33: 0x40d0a5 - std::panicking::try::h5a771d0c48e892af
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345

34: 0x40d0a5 - std::panic::catch_unwind::h870c012436fa44df
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382

35: 0x40d0a5 - std::thread::Builder::spawn_unchecked::{{closure}}::hdecd407cff650c45
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/thread/mod.rs:463

36: 0x40d0a5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he37b03a8f6aa1fa6
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227

37: 0x488e6a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1c9450ee681771f3
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042

38: 0x488e6a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h81e5fd666e5c1445
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042

39: 0x488e6a - std::sys::unix::thread::Thread::new::thread_start::h7ee40607fb4ce1b5
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
```

**Comment by gwenn** [comment]
"no such table: UnicodeData" suggests that SQLite uses an valid but empty database file.
http://sqlite.org/c3ref/db_filename.html may help you.
At least to make sure you are using the right path.
But currently, this method is not available in `rusqlite` public API.
However, temporarily, you can use [Connection::handle](https://docs.rs/rusqlite/0.24.2/rusqlite/struct.Connection.html#method.handle) and copy [this](https://github.com/rusqlite/rusqlite/blob/master/src/lib.rs#L1018-L1026) code.

Another way is to remove the [SQLITE_OPEN_CREATE](https://docs.rs/rusqlite/0.24.2/rusqlite/struct.OpenFlags.html#associatedconstant.SQLITE_OPEN_CREATE) flag where you expect to open an already existing database.

**Comment by pemistahl** [comment]
Thanks for your quick response, @gwenn. 
The path should definitely be correct as it is dynamically determined by the [dirs crate](https://crates.io/crates/dirs). It works on macOS and Windows but not on Ubuntu. I think it's a problem with how different threads in the GitHub actions pipeline try to access the database in the integration test step. I will investigate whether switching the flag while opening the database can solve this problem.

**Comment by pemistahl** [comment]
[The problem still exists](https://github.com/pemistahl/chr/runs/1674207911?check_suite_focus=true#step:8:106) when settings the flag SQLITE_OPEN_READ_ONLY.
The executable path is: `/home/runner/work/chr/chr/target/x86_64-unknown-linux-musl/debug/chr`
The database path is: `/home/runner/.chr/chr_1_0_0.db`

Could it be that the home directory is somehow not readable by the action worker on Ubuntu?

**Comment by gwenn** [comment]
Check the size of `/home/runner/.chr/chr_1_0_0.db`.
Because SQLite will happily open an empty file:
```sh
touch empty.db
sqlite3 -readonly empty.db
```
Also you can do a `PRAGMA quick_check;` after uncompressing the database to make sure all is fine.

**Comment by pemistahl** [comment]
Thanks @gwenn but I'm not convinced that the problem is caused by the database itself. Why should it be empty on Ubuntu while it is working well on macOS and Windows? That doesn't make sense except for a possible bug in rusqlite.

I've opened an [issue](https://github.com/actions/virtual-environments/issues/2409) for the people dealing with the virtual environments for GitHub actions. Perhaps they have an idea what's going on. I will leave this issue here open until a solution is found.

**Comment by pemistahl** [comment]
[A solution was found in the meantime](https://github.com/actions/virtual-environments/issues/2409#issuecomment-758429744). It was the way how Ubuntu handles threads in combination with cargo's multi-threaded execution of unit tests. If you switch the test execution to single-threaded mode, the database is not blocked anymore and can be accessed by all tests.

So, this issue here can be closed. Nevertheless, thanks a lot again @gwenn.
